### PR TITLE
Improve speed of simulations

### PR DESCRIPTION
**Pull request by Tortar**
This gives a 20% speed-up in the single-threaded model at https://github.com/bancaditalia/BeforeIT.jl/blob/main/examples/benchmark_w_matlab.jl#L24, I expected the multi-threaded version to benefit more because we reduced also some allocations, but didn't test it

### CODE REVIEW

**Comment by Tortar** [comment]
Sorry I got fooled by some previous benchmarks, there is still some improvements but it is not 2x as I previously wrote, I edited my main post

**Comment by Tortar** [comment]
same code as in #20

```julia
julia> @benchmark run(parameters, initial_conditions, T) # this PR
BenchmarkTools.Trial: 132 samples with 1 evaluation.
 Range (min … max):  36.550 ms …  41.297 ms  ┊ GC (min … max): 8.72% … 14.80%
 Time  (median):     37.836 ms               ┊ GC (median):    8.46%
 Time  (mean ± σ):   37.910 ms ± 815.271 μs  ┊ GC (mean ± σ):  8.76% ±  1.34%

      ▁    ▁▄▂ ▅▅▄▅▅▂█▂▁▄                                       
  ▅▁▃▁█▃█▆▆███▆██████████▅▅▆▅▃▅▁▃▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▃▃▃▁▁▃ ▃
  36.6 ms         Histogram: frequency by time         41.2 ms <

 Memory estimate: 110.18 MiB, allocs estimate: 670279.

julia> @benchmark run(parameters, initial_conditions, T) # master
BenchmarkTools.Trial: 118 samples with 1 evaluation.
 Range (min … max):  40.662 ms … 52.037 ms  ┊ GC (min … max): 8.02% … 6.88%
 Time  (median):     42.019 ms              ┊ GC (median):    7.65%
 Time  (mean ± σ):   42.583 ms ±  1.657 ms  ┊ GC (mean ± σ):  8.61% ± 2.31%

           █▂█ ▄ ▃ ▄                                           
  ▅▅▁▃▆▃█▆██████▆█▅█▆█▅▁▃▁▁▃▃▁▁▁▁▁▁▁▁▁▁▅▁▃▅▁▁▆▆▃▃▁▁▅▃▃▃▃▁▃▁▁▃ ▃
  40.7 ms         Histogram: frequency by time        46.6 ms <

 Memory estimate: 139.26 MiB, allocs estimate: 679000.
```

yes, nearly 10% :-)

**Comment by AldoGl** [comment]
Thanks @Tortar, squashing and merging now

**Comment by finmod** [comment]
@Tortar Can you see an advantage to bringing agents, agents_actions and markets of BeforeIT and ABCredit within JuliaDynamics/Agents.jl? This would provide better integration with the JuliaDynamics.jl-SciML,jl-ReinforcementLearning.jl ecosystems.  Perhaps a ABM example in AgentsModelZoo... 

See also this question on Discourse: https://discourse.julialang.org/t/specific-dom/121140

**Pull request merged**
