### PR TITLE
Enable Aqua tests

### PR DESCRIPTION
**Pull request by Tortar**
I enabled Aqua tests fixing problems when enabled, it should improve load times because some packages were not necessary to be included in the package, just in the tests. Hope this helps!

### CODE REVIEW

**Comment by Devetak** [comment]
Very cool, thank you for doing this. Aqua seems great.
Should we add the removed dependencies somewhere so that tests still run?
In theory this should not matter as long as one has the required dependencies installed in the global environment right?

**Comment by Tortar** [comment]
tests will run anyway because it has its project.toml with its own dependencies, it will load those dependencies when tests are run

**Comment by AldoGl** [comment]
Well, if tests pass and @Devetak is happy with the change I think we can merge

**Comment by Tortar** [comment]
hope to be able to contribute more to the project, if I can ask: what is your schedule to write the paper? Because I would like to contribute more meaningfully to the project, because I'm pretty interested in it, but maybe that train is already passed...

**Comment by AldoGl** [comment]
@Tortar write me and @Devetak an email to discuss this possibility further. There might be space already for this publication but, most importantly, this could ideally become a long-term project with subsequent updates and future publications

**Comment by Tortar** [comment]
Thanks for considering it, I will get in touch shortly

**Pull request merged**
