### PR TITLE
Custom implementation of weighted sampling

### PR DESCRIPTION
**Pull request by Tortar**
This helps the simulation time, shaving another 15% from the timings of https://github.com/bancaditalia/BeforeIT.jl/blob/main/examples/benchmark_w_matlab.jl#L24. Unfortunately it seems to slightly change the results, this should be  only because the implementation is different from `StatsBase.wsample`

### CODE REVIEW

**Comment by Tortar** [comment]
Fixed the issue with the tests, now everything works the same as before

**Comment by Devetak** [comment]
Great!

**Comment by AldoGl** [comment]
Before merging I would actually make sure we find a non negligible speedup. 
I did run the "benchmark_with_matlabl" script in the examples folder and I could not measure it

**Comment by Tortar** [comment]
The problem is that the GC runs unreliably between runs, so to measure realibly I think we should use `@benchmark` or `@btime`, will come back with the results using them

**Comment by Devetak** [comment]
Confirm @Tortar. With the example from `main.jl` without printing the speed up for me, with a single thread is 50%. 
One thing before merging. In general the function you provide should work best for small-medium sized weights. @AldoGl do we have a larger test case from Poledna's paper?

**Comment by Tortar** [comment]
I guess this should be always be the best algorithm, because I don't think there could exist a case where this function is slower _if_ the simulation is dynamic and we can't reuse the sum of weights between different runs (which is the case here as far as I can tell)

**Comment by Devetak** [comment]
You are absolutely correct! I suggest we merge since it makes the code faster.
I benchmarked the custom weighted sampling with the one from StatsBase and they take the same amount. So I am not sure how the BeforeIT version is so much faster.

```julia
function test(N)
       a = rand(N)
       b = rand(N)
       @btime wsample_single(a, b)
       @btime wsample(a, b)
       end
```

**Comment by Tortar** [comment]
I think because this version is non-allocating so the GC should be triggered less often, it is probably possible to improve the version of StatsBase, but I'm a bit unsure the time it would take, because maintenance is rather slow there (I have some PRs floating around there from months)

**Comment by Tortar** [comment]
I have actually pushed some more improvements exploting the unique properties which are satisfied in this case, now it should be even a bit faster

**Comment by Tortar** [comment]
The last commit broke the tests but it shouldn't have any logical difference between the previous method, it just select differently but with the same probability structure

**Comment by Tortar** [comment]
@Devetak what do you think? It seems to me that we merge this one after adjusting tests

**Comment by Devetak** [comment]
> @Devetak what do you think? It seems to me that we merge this one after adjusting tests

Few sparse comments:
(a) see also comment on Issue #25, I think some of the later changes make the code less readable. So I will keep `deleteat!` or put a comment
(b) the test that fail are the ones that compare with matlab. hence the most important ones! We should not change those. Those are the most important ones.

Btw the bug is the change of `deleteat!` I think. Since

`deleteat!([a,b,c,d], 2) = [a,c,d]` but

```julia
F_g[e], F_g[end] = F_g[end], F_g[e] # [a,d,c,e]
pop!(F_g) # [a,d,c]
```

In practice they are equivalent, but making it impossible to compare to Matlab is in my opinion not worth it. That is really the most important check! How much speed up there is from that?

**Comment by Tortar** [comment]
It has a big impact (something like 30 seconds in the big models with scale=0.01) but let's keep this simple and discuss possible improvements later, so I will just remove that improvement. I will just add a function for that for the record. I think that nonetheless we could reproduce the results "in expectation"

**Comment by Tortar** [comment]
Now it should be okay

**Comment by Devetak** [comment]
An idea could be to change swap pop to normal pop for the deterministic run.

**Comment by Tortar** [comment]
you are totally right, we will have to change the some search_and_matching tests but they are not as critical I believe, right?

**Comment by Tortar** [comment]
you can see them here: https://github.com/bancaditalia/BeforeIT.jl/actions/runs/11643028585/job/32423294518?pr=20

Will add a test

**Comment by Devetak** [comment]
I would ask @AldoGl how where the tests constructed and see from there. Definitely important to have comprehensive tests if we are going to work on performance.

**Comment by Tortar** [comment]
Closing in favour of #30

**Pull request closed without merging**
