### PR TITLE
Use inplace conversion

### PR DESCRIPTION
**Pull request by Tortar**
This has some good impact on performance (something like 20% less time)

### CODE REVIEW

**Review by Devetak — CHANGES_REQUESTED** [review]
Hi! Its not clear what the `pos!` function does since it is both in place and returns an array.

**Comment by Devetak** [comment]
Woudn't be better if the function was either pure or in-place with no return. Looking at the use I would say

```julia
expression = pos_inplace(a / sum(a))
# transfor to
expression .= a / sum(a) # in - place 
pos_inplace!(expression)

**Comment by Tortar** [comment]
added some docs and put it next to the not-in-place version

**Comment by Tortar** [comment]
We need the return, otherwise we couldn't use it inside other computations

**Comment by Tortar** [comment]
it's also conventional in Julia (I think for this reason)

**Pull request merged**
